Support scaling changes during ongoing scaling
scylladb/scylla-operator pull request #1283
Opened 2023-06-16 14:56 UTC by zimnx

Decommissioning label reconcilation was moved from StatefulSet controller into Service controller.
StatefulSet controller can now react dynamically to scaling events occuring while scaling operations are still ongoing.

Fixes #1188

2023-07-06 13:39 UTC, rzetelskik requested changes
Overall well done, I like how much more readable the scaling code is now. I left some comments though, especially regarding the edge case of scaling down and up immediatelly.

2023-07-06 13:39 UTC, rzetelskik commented on test/e2e/set/scyllacluster/scyllacluster_scaling.go
> +	g.It("should react on scaling up in the middle of scaling down", func() {
```suggestion
	g.It("should react to scaling up in the middle of scaling down", func() {
```

2023-07-06 13:39 UTC, rzetelskik commented on test/e2e/set/scyllacluster/scyllacluster_scaling.go
> +	g.It("should react on scaling down in the middle of scaling up", func() {
```suggestion
	g.It("should react to scaling down in the middle of scaling up", func() {
```

2023-07-20 16:44 UTC, tnozicka commented on test/e2e/utils/helpers.go
> +		return "", fmt.Errorf("service %s/%s is of type %q instead of %q", s.Namespace, s.Name, s.Spec.Type, corev1.ServiceTypeClusterIP)
kobj is to be used with klog, there is an equivalent function in naming package for everything else

2024-09-17 10:45 UTC, closed without merging