docs: remove custom md extension
scylladb/scylla-operator pull request #1661
Opened 2023-12-26 10:53 UTC by dgarcia360

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/168

Replaces the project-specific Markdown extension with the sphinx-scylladb-markdown extension from [sphinx-scylladb-theme](https://github.com/scylladb/sphinx-scylladb-theme/tree/master/extensions/sphinx-scylladb-markdown), available on PyPI for all projects.

## How to test

Docs should be built and rendered without errors.

2023-12-27 07:23 UTC, tnozicka commented
/ok-to-test

2023-12-27 07:24 UTC, tnozicka commented
/cc @rzetelskik

2023-12-27 10:23 UTC, rzetelskik requested changes
@dgarcia360 thanks, left one comment. Could you also please update the commit name to align with our repository? Something along the lines of `Replace project-specific scylladb_markdown extension with sphinx-scylladb-markdown extension` (or at least remove the `docs:` prefix).

2023-12-27 10:23 UTC, rzetelskik commented on docs/source/conf.py
> -myst_heading_anchors = 6
This line is added in the first commit and then removed in the second. Please squash the commits.

2024-01-02 13:01 UTC, rzetelskik commented
/retest-required

2024-01-02 17:52 UTC, dgarcia360 commented
> Could you also please update the commit name to align with our repository?

Done!

2024-01-02 17:54 UTC, rzetelskik commented
/lgtm
/assign tnozicka

2024-01-02 18:05 UTC, tnozicka approved these changes
/approve
/lgtm

thanks!

2024-01-02 18:06 UTC, merged