Drain the node before Pod is terminated
scylladb/scylla-operator pull request #1707
Opened 2024-01-26 11:18 UTC by zimnx

Draining node before SIGTERM gracefully shuts down and allows for finishing inflight requests, and prevents new ones.

/cc tnozicka

Part of bigger PR https://github.com/scylladb/scylla-operator/pull/1614

2024-01-26 14:03 UTC, tnozicka requested changes

2024-01-26 14:03 UTC, tnozicka commented on pkg/controller/scyllacluster/resource.go
> +											"/bin/sh", "-c", "nodetool drain; sleep 15",
I think any sleep here needs to be configurable, given how LB are (not) integrated / the unpredictability of any network. The approach here also depends on what happens when a new connections arrives after the drain. Does it need to be drained again? Does scylla refuse a new connection after drain? Depending on the answer I see 2 algorithms:

a)
1. `sleep <minTerminationPeriod>`
1. `nodetool drain`

b) 
1. `sleep <minTerminationPeriod> &`
1. `nodetool drain &`
1. `wait`

2024-01-26 14:03 UTC, tnozicka commented on pkg/controller/scyllacluster/resource.go
> -											"/bin/sh", "-c", "PID=$(pgrep -x scylla);supervisorctl stop scylla; while kill -0 $PID; do sleep 1; done;",
Can you clarify why this was needed before and not after? Does the SIGTERM (after preStop hook) propagate correctly now?

2024-01-26 15:02 UTC, tnozicka commented on pkg/controller/scyllacluster/resource.go
> -											"/bin/sh", "-c", "PID=$(pgrep -x scylla);supervisorctl stop scylla; while kill -0 $PID; do sleep 1; done;",
synced on a call, this is fine as SIGTERM now works

2024-01-26 15:03 UTC, tnozicka commented on pkg/controller/scyllacluster/resource.go
> +											"/bin/sh", "-c", "nodetool drain; sleep 15",
synced on call, going with b)

2024-01-29 15:43 UTC, tnozicka commented on pkg/controller/scyllacluster/resource.go
> +											"/bin/sh", "-c",
-eUeo pipefail and err_exit?

2024-01-29 16:59 UTC, zimnx commented on pkg/api/scylla/v1/types_cluster.go
> +	MinNodeTerminationPeriod *metav1.Duration `json:"minNodeTerminationPeriod,omitempty"`
done

2024-01-29 16:59 UTC, zimnx commented on pkg/api/scylla/v1/types_cluster.go
> +	MinNodeTerminationPeriod *metav1.Duration `json:"minNodeTerminationPeriod,omitempty"`
done

2024-01-29 16:59 UTC, zimnx commented on pkg/controller/scyllacluster/resource.go
> +											"/bin/sh", "-c",
done

2024-01-30 16:59 UTC, zimnx commented on pkg/api/scylla/v1/types_cluster.go
> +	// If not provided, Operator will choose this value.
done

2024-01-30 17:26 UTC, tnozicka approved these changes
/lgtm
thanks!

2024-01-31 09:47 UTC, zimnx commented
https://github.com/scylladb/scylla-operator/issues/1694#issuecomment-1918746437
https://github.com/scylladb/scylla-operator/issues/1028#issuecomment-1918747044
/retest

2024-01-31 11:02 UTC, merged