Make io setup optional when starting scyllaDB container
scylladb/scylla-operator pull request #175
Opened 2020-08-12 16:36 UTC by erebe

+ Related to #146 to avoid long startup time

When we provision our machines, we pre-configure them in order to get the correct configuration for scyllaDB. 
Thus running io-setup at startup takes a long time and duplicate effort in our case.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Image has been built (`make docker-build`) on the last commit.

2020-08-20 08:41 UTC, zimnx requested changes
We must reject setting this option together with Scylla version which doesn't support it. 
Please add validation check to https://github.com/scylladb/scylla-operator/blob/d75aaad0c77436611a36fc29b41c7acb34ed5cce/pkg/api/v1alpha1/cluster_validation.go

2020-08-20 08:41 UTC, zimnx commented on config/crd/bases/scylla.scylladb.com_clusters.yaml
> +            ioSetup:
add note about which Scylla version supports this flag

2020-08-20 08:41 UTC, zimnx commented on pkg/controllers/sidecar/config/config.go
> +		fmt.Sprintf("--io-setup=%s", ioSetup),
Don't append it when it's not supported for deployed Scylla version.

2020-08-28 09:01 UTC, erebe commented
Thanks for the review, i am on vacation right nlw. i am going to check thzt in september when i am back

2020-08-31 10:07 UTC, erebe commented
Sorry for the disturbance, I am moving the PR to https://github.com/scylladb/scylla-operator/pull/179, I forgot to use the special branch I've created to submit the PR.

2020-08-31 10:07 UTC, closed without merging