Update sphinx-scylladb-theme to 1.7.1
scylladb/scylla-operator pull request #1895
Opened 2024-04-15 14:43 UTC by rzetelskik

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #1893

2024-04-15 16:35 UTC, rzetelskik commented
/kind documentation
/priority important-soon

2024-04-16 07:15 UTC, tnozicka requested changes

2024-04-16 07:15 UTC, tnozicka commented on docs/pyproject.toml
> +sphinx-scylladb-theme = "^1.7.1"
```suggestion
sphinx-scylladb-theme = "~1.7.1"
```
`minor` upgrades need manual changes

2024-04-16 08:45 UTC, rzetelskik commented on docs/pyproject.toml
> +sphinx-scylladb-theme = "^1.7.1"
done

2024-04-16 10:00 UTC, tnozicka commented
hm, the menu is gone
/hold

![Screenshot from 2024-04-16 12-00-05](https://github.com/scylladb/scylla-operator/assets/11869554/008605d3-e1d8-4a7b-a4fb-879f01fe63cb)

2024-04-16 10:03 UTC, rzetelskik commented
@tnozicka works for me, including the auto scroll
![image](https://github.com/scylladb/scylla-operator/assets/32443348/f64ea6b0-4676-44b2-a3ca-05ddb79f0b2c)

2024-04-16 12:41 UTC, tnozicka commented
I've run `poetry install && make preview` inside the container. That used to work before, I can try this on a clean system if you confirm it works for you but there can be something hidden related to the upgrade.

2024-04-16 12:43 UTC, tnozicka commented
> make setup dirhtml multiversionpreview

btw. those are run in parallel / racy (modulo explicit deps order)

2024-04-16 14:38 UTC, rzetelskik commented
`podman run -it --pull=Always --rm -v="$( pwd )/docs:/go/$( go list -m )/docs:Z" --workdir="/go/$( go list -m )/docs" -p 5500:5500 quay.io/scylladb/scylla-operator-images:poetry-1.5 bash -euExo pipefail -O inherit_errexit -c 'poetry install && make preview'` 

This also works fine for me.

![image](https://github.com/scylladb/scylla-operator/assets/32443348/74c8367b-130d-4c68-a4ca-11515e9d45cb)

Did you clean the build dir before running it?

2024-04-17 06:55 UTC, tnozicka commented
never had to but it helped
/shrug

/approve
/lgtm

2024-04-17 06:57 UTC, rzetelskik commented
@tnozicka can we cancel the hold then?

2024-04-17 07:25 UTC, merged